# Generated by Django 5.2.4 on 2025-07-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudo',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
